- name: Configuring standard operating parameters
  hosts:
    - federation
  gather_facts: yes
  sudo: true
  roles:
    - { role: base, tags: [ 'base' ] }
    - { role: internet-base, tags: [ 'internet-base', 'internet' ] }
    - { role: mail, tags: [ 'mail' ] }
    - { role: multimedia, tags: [ 'multimedia' ] }
    - { role: firefox, tags: [ 'firefox', 'internet' ] }
    - { role: google, tags: [ 'google', 'internet' ] }
  
