---

- name: Configuring standard operating parameters
  hosts: localhost
  gather_facts: yes
  sudo: true
  vars_files:
    - vars/secrets.yml
  roles:
    - { role: base, tags: [ 'base' ] }
    - { role: standard, tags: [ 'standard' ] }
    - { role: audio, tags: [ 'audio' ] }
    - { role: internet-base, tags: [ 'internet-base', 'internet' ] }
    - { role: japanese, tags: [ 'japanese' ] }
    - { role: mail, tags: [ 'mail' ] }
    - { role: development, tags: [ 'development' ] }
    - { role: multimedia, tags: [ 'multimedia' ] }
    - { role: firefox, tags: [ 'firefox', 'internet' ] }
    - { role: google, tags: [ 'google', 'internet' ] }
    - { role: libreoffice, tags: [ 'libreoffice' ] }
  
