---
- name: Set install to unstable
  template: dest=/etc/apt/sources.list src=etc-apt-sources.list.j2  

- name: Update system to unstable
  apt: upgrade=dist
  when: distupgrade is defined

- name: Add owncloud key
  apt_key: url=http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_8.0/Release.key state=present

- name: Update apt cache (we only want to do this once)
  apt: update_cache=yes

- name: Ensure local directories exist
  file: path="/home/{{item[0]}}/{{item[1]}}" state=directory owner="{{item[0]}}" group="{{item[0]}}"
  with_nested:
    - crew
    - [ 'local', 'src' ]

- name: Ensure local directories exist
  file: path="/home/{{item[0]}}/{{item[1]}}" src="/home/{{item[0]}}/MEGA/bin" state=link owner="{{item[0]}}" group="{{item[0]}}"
  with_nested:
    - crew
    - [ 'bin' ]
