---
- name: Ensure local directories exist
  file: path="/home/{{item[0]}}/{{item[1]}}" state=directory owner="{{item[0]}}" group="{{item[0]}}"
  with_nested:
    - crew
    - [ 'bin', 'local', 'src' ]

- name: Install standard apps
  apt: name="{{ item }}" state=latest update_cache=true
  with_items: standard_apps
