---
- name: Set install to unstable
  template: dest=/etc/apt/sources.list src=etc-apt-sources.list.j2  

- name: Update system to unstable
  apt: upgrade=dist
  when: distupgrade is defined

- name: Update apt cache (we only want to do this once)
  apt: update_cache=yes

- name: Ensure local directories exist
  file: path="/home/{{item[0]}}/{{item[1]}}" state=directory owner="{{item[0]}}" group="{{item[0]}}"
  with_nested:
    - crew
    - [ 'bin', 'local', 'src' ]

