---
  - name: Add Google repositories
    apt_repository: repo="{{ item }}" state=present
    with_items:
      - "deb http://dl.google.com/linux/talkplugin/deb/ stable main"
      - "deb http://dl.google.com/linux/chrome/deb/ stable main"

  - name: Install Google apps
    apt: name="{{ item }}" state=latest update_cache=true
    with_items:
      - google-talkplugin
      - google-chrome-stable
